<a href="https://colab.research.google.com/github/MikolajKasprzyk/data_science_bootcamp/blob/main/01_wprowadzenie/03_funkcje_statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
price = np.array([[12.40, 12.80, 11.90, 12.60, 1000],
                  [12.50, 13.00, 11.70, 12.20, 2000],
                  [12.20, 13.40, 12.20, 13.20, 1500]])
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


sum()

In [ ]:
price(sum) # suma wszystkich elementów w tablicy - mało przydatne

In [ ]:
price.sum(axis=0) #sumowanie po kolumnach najczęsciej 
price.sum(axis=10) #sumowanie po wierszach

In [4]:
np.sum(price, axis=0) #możemy to wywołać też w taki sposób

array([  37.1,   39.2,   35.8,   38. , 4500. ])

min()

In [5]:
np.min(price, axis=0)
#osie działają analogicznie jak w sum()

array([  12.2,   12.8,   11.7,   12.2, 1000. ])

max()

In [ ]:
np.max(price, axis=0)
#osie działają analogicznie jak w sum()

median()

In [8]:
np.median(price, axis=1)
#osie działają analogicznie jak w sum()

array([12.6, 12.5, 13.2])

mean()

In [11]:
np.mean(price, axis=0)
#osie działają analogicznie jak w sum()

array([209.94, 409.88, 310.2 ])

std()

In [ ]:
np.std(price, axis=0)

var()

In [13]:
np.var(price, axis=0)

array([1.55555556e-02, 6.22222222e-02, 4.22222222e-02, 1.68888889e-01,
       1.66666667e+05])