<a href="https://colab.research.google.com/github/MikolajKasprzyk/data_science_bootcamp/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Spis treści:
1. [Podstawy](#a1)
2. [Typy danych](#a2)
3. [Tworzenie tablic](#a3)
4. [Podstawowe operacje na tablicach](#a4)
5. [Generowanie liczb pseudolosowych](#a5)
6. [Podstawowe funkcje](#a6)
7. [Indeksowanie, Wycinanie](#a7)
8. [Iteracja po tablicach](#a8)
9. [Zmiana rozmiaru tablic](#a9)
10. [Maski logiczne](#a10)

### <a name='a1'></a> Podstawy

In [13]:
import numpy as np
np.__version__

'1.22.4'

In [ ]:
dir(np)

In [ ]:
help(np.array)

1D Array

In [16]:
x = np.array([1, 3])
x

array([1, 3])

In [17]:
print(x)

[1 3]


In [18]:
type(x)

numpy.ndarray

In [19]:
x.ndim # wymiar tablicy
x.shape # kształt tablicy
x.size # rozmiar - liczba elementów w tablicy
x.dtype # typ danych tablicy

dtype('int64')

In [20]:
y = np.array([1.3, 2.3, 2.4])
print(y)

[1.3 2.3 2.4]


In [22]:
y.dtype

dtype('float64')

2D Array

In [25]:
x = np.array([[1,2], [-3, 1]])
print(x)

[[ 1  2]
 [-3  1]]


In [26]:
x.ndim

2

In [27]:
x.shape

(2, 2)

In [29]:
x = np.array([[1, 2, 3], [4, 2, 1]])
print(x)

[[1 2 3]
 [4 2 1]]


In [30]:
x.shape

(2, 3)

3D Array

In [32]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
      
      [[4, 1, 3],
       [4, 2, 1]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [33]:
x.ndim

3

In [34]:
x.shape

(2, 2, 3)

### <a name='a2'></a> Typy danych


In [35]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [37]:
A = np.array([1, 2, 3], dtype='float') # ustawienie typu danych z palca
A.dtype

dtype('float64')

In [40]:
# taki manewr zmieni nam typ ale rowniez zaokragli liczby
A = np.array([1.3, 2.6, 3.1], dtype='int')
A.dtype
print(A)

[1 2 3]


In [42]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [43]:
A = np.array([24, 120, 230], dtype=np.int8) # liczby int 8-bitowe

In [ ]:
A = np.array([24, 120, 230], dtype=np.iunt8) # unsigned int 8-bitowe

### <a name='a3'></a> Tworzenie tablic

In [45]:
# tworzenie tablicy z zerami o zadanym wymiarze
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [47]:
# tworzenie tablicy z jedynkami o zadanym wymiarze
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [48]:
# tworzenie tablicy o zadanej wartosci o zadanym wymiarze
np.full(shape=(5, 5), fill_value=4, dtype='int')

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [50]:
# tworzy tablice z zadanych liczb
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
# tworzy tablice z zadanych liczb
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [54]:
# przedział i zadana liczba elementów w rownych odleglosciach
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [59]:
A = np.arange(15)
A.reshape((3, 5)) # zmiana kształtu tablicy (nie zmienia oryginału)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [60]:
A.reshape((3, -1)) # z automatu dobiera liczbe kolumn, dziala tez na odwrot

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### <a name='a4'></a> Podstawowe opercje na tablicach

In [61]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [62]:
A + B

array([6, 0, 7, 4])

In [63]:
A - B

array([0, 2, 1, 0])

In [64]:
A * B

array([ 9, -1, 12,  4])

In [65]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [66]:
A + 3 # dodaje 3 do kazdego elementu
# analogicznie działa z innymi działaniami

array([6, 4, 7, 5])

In [ ]:
# podtsawowe działania w numpy - dziła jak to powyzej
np.add(A, B)
np.subtract(A, B)
np.multiply(A, B)
np.divide(A, B)

In [67]:
A + 3*B

array([12, -2, 13,  8])

Mnożenie macierzowe

In [69]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X)
print(Y)

[[ 1  3]
 [-2  0]]
[[ 6  0]
 [-1  2]]


In [70]:
 np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
X.dot(Y)
Y.dot(X)
# mnożenie macierzy nie jest przemienne

In [ ]:
X @ Y # mnożenie macierzy przy użyciu symbolu - to samo co metoda dot

### <a name='a5'></a> Generowanie liczb pseudolosowych

In [71]:
np.random.seed(0)

In [72]:
np.random.randn(10) # losowy rozkład normalny

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ])

In [73]:
np.random.randn(10, 4) # losowa tablica o zadanym rozmiarze

array([[ 0.14404357,  1.45427351,  0.76103773,  0.12167502],
       [ 0.44386323,  0.33367433,  1.49407907, -0.20515826],
       [ 0.3130677 , -0.85409574, -2.55298982,  0.6536186 ],
       [ 0.8644362 , -0.74216502,  2.26975462, -1.45436567],
       [ 0.04575852, -0.18718385,  1.53277921,  1.46935877],
       [ 0.15494743,  0.37816252, -0.88778575, -1.98079647],
       [-0.34791215,  0.15634897,  1.23029068,  1.20237985],
       [-0.38732682, -0.30230275, -1.04855297, -1.42001794],
       [-1.70627019,  1.9507754 , -0.50965218, -0.4380743 ],
       [-1.25279536,  0.77749036, -1.61389785, -0.21274028]])

In [74]:
np.random.rand() # losowa wartosc z przedzialu 0 1

0.15896958364551972

In [75]:
np.random.rand(10)

array([0.11037514, 0.65632959, 0.13818295, 0.19658236, 0.36872517,
       0.82099323, 0.09710128, 0.83794491, 0.09609841, 0.97645947])

In [76]:
np.random.rand(8, 7)

array([[0.4686512 , 0.97676109, 0.60484552, 0.73926358, 0.03918779,
        0.28280696, 0.12019656],
       [0.2961402 , 0.11872772, 0.31798318, 0.41426299, 0.0641475 ,
        0.69247212, 0.56660145],
       [0.26538949, 0.52324805, 0.09394051, 0.5759465 , 0.9292962 ,
        0.31856895, 0.66741038],
       [0.13179786, 0.7163272 , 0.28940609, 0.18319136, 0.58651293,
        0.02010755, 0.82894003],
       [0.00469548, 0.67781654, 0.27000797, 0.73519402, 0.96218855,
        0.24875314, 0.57615733],
       [0.59204193, 0.57225191, 0.22308163, 0.95274901, 0.44712538,
        0.84640867, 0.69947928],
       [0.29743695, 0.81379782, 0.39650574, 0.8811032 , 0.58127287,
        0.88173536, 0.69253159],
       [0.72525428, 0.50132438, 0.95608363, 0.6439902 , 0.42385505,
        0.60639321, 0.0191932 ]])

In [77]:
np.random.randint(10) # losuje od 0 do 10 (max 9)

5

In [79]:
np.random.randint(low=10, high=101, size=(8, 4))

array([[23, 81, 66, 34],
       [89, 51, 28, 50],
       [64, 89, 21, 48],
       [11, 54, 98, 34],
       [77, 92, 13, 86],
       [45, 96, 71, 79],
       [97, 53, 42, 21],
       [94, 20, 64, 47]])

In [80]:
np.random.choice([4, 2, 1, 4]) # zwraca losowy element z zadanego obiektu

2

In [81]:
np.random.choice(['python', 'java', 'sql'])

'python'

In [82]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
# tasuje dane - zmienia oryginał
np.random.shuffle(data)
data

array([6, 4, 0, 2, 1, 7, 5, 3, 8, 9])

### <a name='a6'></a> Podstawowe funkcje 

In [85]:
np.exp(1) # liczba e do potegi 1

2.718281828459045

In [91]:
np.sqrt(9)

3.0

In [89]:
np.all([2, 3, 1]) # jesli wszystkie prawda to zwraca prawde

20.085536923187664