<a href="https://colab.research.google.com/github/MikolajKasprzyk/data_science_bootcamp/blob/main/06_TensorFlow_Keras/02_keras_wprowadzenie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%tensorflow_version 2.x
import tensorflow as tf
import numpy as np
import pandas as pd
import plotly.express as px
tf.__version__

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


'2.12.0'

# Model sekwencyjny to liniowy stos warstw

In [ ]:
# utworzenie instancji klasy Sequential
from tensorflow.keras.models import Sequential

model = Sequential()
print(model)

In [ ]:
# podastawowym elementami sieci neuronowej są warstwy
# najbardziej podstaowowa warstwa gesto polaczona Dense
from tensorflow.keras.layers import Dense

model.add(Dense(units=4, input_shape=(10,)))
# units to liczba neuronow, input shape to rozmiar danych wejsciowych
# czyli 10 cech to bedzie (10,) jesli to obraz to podajemy jego rozmiar np (28,28)

In [ ]:
# podstawowy opis modelu

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_5 (Dense)             (None, 4)                 44        
                                                                 
Total params: 44
Trainable params: 44
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.add(Dense(units=2))

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_5 (Dense)             (None, 4)                 44        
                                                                 
 dense_6 (Dense)             (None, 2)                 10        
                                                                 
Total params: 54
Trainable params: 54
Non-trainable params: 0
_________________________________________________________________


### <a name='a1'></a>Funkcje aktywacji
Istotnym elemenem sieci neuronowych jest dobór odpowiednich funkcji aktywacji. Funkcje aktywacji jak sama nazwa wskazuje są odpowiedzialne za aktywowanie odpowiednich neuronów podczas procesu uczenia.

Jeżeli nie określimy podczas dodawania warstwy funkcji aktywacji, domyślnie stosowana jest liniowa funkcja aktywacji, tzn. $a(x)=x$

Warstwa z liniową funkcją aktywacji może uczyć się tylko liniowych przekształceń danych wejściowych. Dlatego stosuje się różne funkcje aktywacji aby rozwiazywać problemy nieliniowe.

[Keras: Funkcje aktywacji](https://keras.io/activations/)

In [ ]:
from tensorflow.keras.activations import linear # domyslna funkcja aktywacji

random_data = np.linspace(start=-3, stop=3, num=300)
data = pd.DataFrame({'data': random_data, 'linear': linear(random_data)})
data.head()

# ta funcja w sumie nic nie robi, zwraca to samo

data    linear
0 -3.000000 -3.000000
1 -2.979933 -2.979933
2 -2.959866 -2.959866
3 -2.939799 -2.939799
4 -2.919732 -2.919732

In [ ]:
px.line(data, x=data['data'], y=data['linear'],width=500, height=400)

In [ ]:
from tensorflow.keras.activations import sigmoid # popularna funkcja w ostanich warstwach jesli chcemy zwracac prawdopodobienstwo

random_data = np.linspace(start=-3, stop=3, num=300)
data = pd.DataFrame({'data': random_data, 'sigmoid': sigmoid(random_data)})
print(data.head())

# ta funcja w sumie nic nie robi, zwraca to samo

px.line(data, x=data['data'], y=data['sigmoid'],width=500, height=400)

       data   sigmoid
0 -3.000000  0.047426
1 -2.979933  0.048341
2 -2.959866  0.049272
3 -2.939799  0.050221
4 -2.919732  0.051187


In [ ]:
from tensorflow.keras.activations import relu # zeruje wartosci ujemne, radzi sobie z nieliniowoscia

random_data = np.linspace(start=-3, stop=3, num=300)
data = pd.DataFrame({'data': random_data, 'relu': relu(random_data)})
print(data.head())

# ta funcja w sumie nic nie robi, zwraca to samo

px.line(data, x=data['data'], y=data['relu'],width=500, height=400)

       data  relu
0 -3.000000   0.0
1 -2.979933   0.0
2 -2.959866   0.0
3 -2.939799   0.0
4 -2.919732   0.0


In [ ]:
from tensorflow.keras.activations import tanh # jak sigmoid sobie nie radzi to moze byc dobre zastepstwo

random_data = np.linspace(start=-3, stop=3, num=300)
data = pd.DataFrame({'data': random_data, 'tanh': tanh(random_data)})
print(data.head())

# ta funcja w sumie nic nie robi, zwraca to samo

px.line(data, x=data['data'], y=data['tanh'],width=500, height=400)

       data      tanh
0 -3.000000 -0.995055
1 -2.979933 -0.994853
2 -2.959866 -0.994643
3 -2.939799 -0.994424
4 -2.919732 -0.994196


# Tworzymy nowy model

In [ ]:
model = Sequential()
model.add(Dense(units=8, activation='relu', input_shape=(10,)))
model.add(Dense(units=1, activation='sigmoid')) # jedna klasa do przewidzenia czyli klasyfikacja binarna
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_7 (Dense)             (None, 8)                 88        
                                                                 
 dense_8 (Dense)             (None, 1)                 9         
                                                                 
Total params: 97
Trainable params: 97
Non-trainable params: 0
_________________________________________________________________


<a name='a2'></a>Kompilacja modelu
Przed rozpoczęciem trenowania sieci należy odpowiednio skonfigurować proces uczenia. W tym kroku określamy:
* rodzaj optymalizatora ([Keras - Optymalizatory](https://keras.io/optimizers/))
* funkcję straty ([Keras - Funkcje Straty](https://keras.io/losses/))
* metryki, które będziemy obserwować podczas trenowania sieci ([Keras - Metryki](https://keras.io/metrics/))

In [ ]:
# klasyfikacja binarna
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# klasyfikacja wieloklasowa
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# regresja
model.compile(optimizer='rmsprop',
              loss='mse') # metryka tu bedzie tez mse

### <a name='a3'></a>Trenowanie modelu
Za dane wejściowe do modelu należy przekazać Numpy arrays:
* **epochs** - krotność przejścia danych przez sieć w procesie uczenia
* **batch_size** - rozmiar wsadu po którym następuje aktualizacja wag
* **validation_split** - część danych treningowych, które zostaną wykorzystane jako zbiór walidacyjny, dzieki temu widac przy uczeniu modelu jak zachowuje sie z danymi których nie widział
* **validation_data** - (x_val, y_val) - dane wykorzystane do walidacji modelu, juz na gotowym zbiorze danych walidacyjnych

In [ ]:
# model.fit(data, labels, epochs=10, batch_size=32)
# model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)
# model.fit(data, labels, epochs=10, batch_size=32, validation_data=(x_val, y_val))

### <a name='a4'></a> Przykład - klasyfikacja binarna

In [ ]:
data = np.random.randn(10000, 150) # 10000 samples, 150 columns
labels = np.random.randint(2, size=(10000, 1))

print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [ ]:
data[:3]

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid')) # jedna klasa do przewidzenia, chcemy prawdopodobienstwa sad sigmoid
model.compile(optimizer='rmsprop', loss='binary_crossentropy',
              metrics=['accuracy'])
model.fit(data, labels, epochs=20)

Epoch 1/20
313/313 [==============================] - 1s 2ms/step - loss: 0.7377 - accuracy: 0.5020
Epoch 2/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6923 - accuracy: 0.5446
Epoch 3/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6746 - accuracy: 0.5742
Epoch 4/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6608 - accuracy: 0.5981
Epoch 5/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6475 - accuracy: 0.6231
Epoch 6/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6328 - accuracy: 0.6459
Epoch 7/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6183 - accuracy: 0.6603
Epoch 8/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6035 - accuracy: 0.6794
Epoch 9/20
313/313 [==============================] - 1s 2ms/step - loss: 0.5889 - accuracy: 0.6963
Epoch 10/20
313/313 [==============================] - 1s 2ms/step - loss: 0.5744 - accuracy: 0.7083

In [ ]:
# dodawanie kolejnych parametrow
model.fit(data, labels, epochs=20, batch_size=64)


Epoch 1/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6297 - accuracy: 0.6487
Epoch 2/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6186 - accuracy: 0.6629
Epoch 3/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6081 - accuracy: 0.6765
Epoch 4/20
157/157 [==============================] - 0s 2ms/step - loss: 0.5975 - accuracy: 0.6870
Epoch 5/20
157/157 [==============================] - 0s 2ms/step - loss: 0.5869 - accuracy: 0.6951
Epoch 6/20
157/157 [==============================] - 0s 2ms/step - loss: 0.5767 - accuracy: 0.7049
Epoch 7/20
157/157 [==============================] - 0s 2ms/step - loss: 0.5667 - accuracy: 0.7158
Epoch 8/20
157/157 [==============================] - 1s 3ms/step - loss: 0.5572 - accuracy: 0.7230
Epoch 9/20
157/157 [==============================] - 0s 3ms/step - loss: 0.5482 - accuracy: 0.7279
Epoch 10/20
157/157 [==============================] - 0s 3ms/step - loss: 0.5390 - accuracy: 0.7333

In [ ]:
# model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid')) # jedna klasa do przewidzenia, chcemy prawdopodobienstwa sad sigmoid
model.compile(optimizer='rmsprop', loss='binary_crossentropy',
              metrics=['accuracy'])
# tu dostajemy tez accuracy i loss na zbiorze walidacyjnym co jest bardziej miarodajne niz na danych trningowych
# tu jako ze dane sa losowe widac ze accuracy poprawia sie na zbiorze treningowym ale na walidacyjnym nie
# wiec mozna sie spodziewac ze taki model jest nie dzialajacy
model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2)

Epoch 1/20
250/250 [==============================] - 1s 3ms/step - loss: 0.6310 - accuracy: 0.6696 - val_loss: 0.5880 - val_accuracy: 0.7335
Epoch 2/20
250/250 [==============================] - 1s 3ms/step - loss: 0.5483 - accuracy: 0.7761 - val_loss: 0.5359 - val_accuracy: 0.7650
Epoch 3/20
250/250 [==============================] - 1s 2ms/step - loss: 0.4808 - accuracy: 0.8039 - val_loss: 0.5190 - val_accuracy: 0.7605
Epoch 4/20
250/250 [==============================] - 1s 2ms/step - loss: 0.4386 - accuracy: 0.8190 - val_loss: 0.5322 - val_accuracy: 0.7435
Epoch 5/20
250/250 [==============================] - 1s 3ms/step - loss: 0.4157 - accuracy: 0.8281 - val_loss: 0.5537 - val_accuracy: 0.7330
Epoch 6/20
250/250 [==============================] - 1s 3ms/step - loss: 0.3971 - accuracy: 0.8363 - val_loss: 0.5784 - val_accuracy: 0.7300
Epoch 7/20
250/250 [==============================] - 1s 4ms/step - loss: 0.3820 - accuracy: 0.8454 - val_loss: 0.6062 - val_accuracy: 0.7210
Epoch 

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid')) # jedna klasa do przewidzenia, chcemy prawdopodobienstwa sad sigmoid
model.compile(optimizer='rmsprop', loss='binary_crossentropy',
              metrics=['accuracy'])
# nie wyswieltamy tekstu podczas trenowania
model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=0)

In [ ]:
# takie modele zwracaja obiekt keras.callbacks.History ktory mozna przpisac do zmiennej
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid')) # jedna klasa do przewidzenia, chcemy prawdopodobienstwa sad sigmoid
model.compile(optimizer='rmsprop', loss='binary_crossentropy',
              metrics=['accuracy'])
# nie wyswieltamy tekstu podczas trenowania
history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=0)
# teraz do danych z trenowania mozna dostac sie przez ta zmienna

In [ ]:
history.history # w atrybucie history sa zaoisane dane z trenowania

{'loss': [0.7545412182807922,
  0.6917606592178345,
  0.6703227758407593,
  0.6528350114822388,
  0.6380449533462524,
  0.6219736933708191,
  0.6071222424507141,
  0.5917048454284668,
  0.5756685137748718,
  0.5608251690864563,
  0.5467976927757263,
  0.5322830080986023,
  0.5191525220870972,
  0.506120502948761,
  0.4933156371116638,
  0.48157644271850586,
  0.47018855810165405,
  0.45914801955223083,
  0.44859495759010315,
  0.43933430314064026],
 'accuracy': [0.5051249861717224,
  0.5566250085830688,
  0.5853750109672546,
  0.6131250262260437,
  0.6388750076293945,
  0.6620000004768372,
  0.675000011920929,
  0.6977499723434448,
  0.7124999761581421,
  0.7237499952316284,
  0.7310000061988831,
  0.7463750243186951,
  0.7543749809265137,
  0.7647500038146973,
  0.768875002861023,
  0.7757499814033508,
  0.7871249914169312,
  0.7892500162124634,
  0.7921249866485596,
  0.8017500042915344],
 'val_loss': [0.7215569615364075,
  0.719264805316925,
  0.7203945517539978,
  0.723952531814575

In [ ]:
# takie modele zwracaja obiekt keras.callbacks.History ktory mozna przpisac do zmiennej
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid')) # jedna klasa do przewidzenia, chcemy prawdopodobienstwa sad sigmoid
model.compile(optimizer='rmsprop', loss='binary_crossentropy',
              metrics=['accuracy'])
# nie wyswieltamy tekstu podczas trenowania
history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=1)
# teraz do danych z trenowania mozna dostac sie przez ta zmienna

Epoch 1/20
250/250 [==============================] - 1s 3ms/step - loss: 0.7459 - accuracy: 0.5015 - val_loss: 0.7223 - val_accuracy: 0.5140
Epoch 2/20
250/250 [==============================] - 1s 2ms/step - loss: 0.6949 - accuracy: 0.5493 - val_loss: 0.7173 - val_accuracy: 0.5060
Epoch 3/20
250/250 [==============================] - 1s 2ms/step - loss: 0.6753 - accuracy: 0.5855 - val_loss: 0.7150 - val_accuracy: 0.5210
Epoch 4/20
250/250 [==============================] - 1s 2ms/step - loss: 0.6601 - accuracy: 0.6062 - val_loss: 0.7177 - val_accuracy: 0.5095
Epoch 5/20
250/250 [==============================] - 1s 2ms/step - loss: 0.6460 - accuracy: 0.6261 - val_loss: 0.7204 - val_accuracy: 0.5065
Epoch 6/20
250/250 [==============================] - 1s 2ms/step - loss: 0.6319 - accuracy: 0.6503 - val_loss: 0.7249 - val_accuracy: 0.5080
Epoch 7/20
250/250 [==============================] - 1s 2ms/step - loss: 0.6170 - accuracy: 0.6678 - val_loss: 0.7280 - val_accuracy: 0.4990
Epoch 

In [ ]:
test_data = np.random.randn(5, 150)
test_labels = np.random.randint(2, size=(5,1))

In [ ]:
model.predict(test_data)

1/1 [==============================] - 0s 96ms/step


array([[0.61694264],
       [0.6943955 ],
       [0.5675323 ],
       [0.11363933],
       [0.37193477]], dtype=float32)

# Klasyfikacja wieloklasowa

In [ ]:
data = np.random.randn(10000, 150) # 10000 samples, 150 columns
labels = np.random.randint(10, size=(10000, 1)) # tutaj mamy 10 klas do przewidzenia

print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [ ]:
labels[:10]

array([[1],
       [1],
       [6],
       [1],
       [4],
       [7],
       [3],
       [5],
       [7],
       [7]])

In [ ]:
# tworzy z kazdej klasy odpowiednio kolumne i przypisuje 1 w miejscu odpowiadajacym klasie
from tensorflow.keras.utils import to_categorical
labels = to_categorical(labels, num_classes=10)
labels

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.]], dtype=float32)

In [ ]:
labels[1] #index 1 - klasa 1

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(10, activation='softmax'))
# 10 klas do przewidzenia, chcemy prawdopodobienstwa i jest softmax

model.compile(optimizer='rmsprop', loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, batch_size=32, epochs=30, validation_split=0.2)

Epoch 1/30
250/250 [==============================] - 1s 3ms/step - loss: 2.5357 - accuracy: 0.1001 - val_loss: 2.4285 - val_accuracy: 0.1045
Epoch 2/30
250/250 [==============================] - 1s 2ms/step - loss: 2.3423 - accuracy: 0.1269 - val_loss: 2.3819 - val_accuracy: 0.1020
Epoch 3/30
250/250 [==============================] - 1s 2ms/step - loss: 2.2736 - accuracy: 0.1555 - val_loss: 2.3735 - val_accuracy: 0.1015
Epoch 4/30
250/250 [==============================] - 1s 2ms/step - loss: 2.2329 - accuracy: 0.1752 - val_loss: 2.3773 - val_accuracy: 0.1055
Epoch 5/30
250/250 [==============================] - 1s 2ms/step - loss: 2.2029 - accuracy: 0.1916 - val_loss: 2.3829 - val_accuracy: 0.1045
Epoch 6/30
250/250 [==============================] - 1s 2ms/step - loss: 2.1778 - accuracy: 0.2046 - val_loss: 2.3951 - val_accuracy: 0.1020
Epoch 7/30
250/250 [==============================] - 1s 2ms/step - loss: 2.1563 - accuracy: 0.2181 - val_loss: 2.4076 - val_accuracy: 0.1090
Epoch 

In [ ]:
test_data = np.random.random((10,150))
test_data

array([[0.41262391, 0.32577614, 0.31161635, ..., 0.40710442, 0.50107294,
        0.74723279],
       [0.73995862, 0.3417131 , 0.41225676, ..., 0.09906019, 0.17496678,
        0.46060977],
       [0.03575729, 0.418204  , 0.94223411, ..., 0.78281068, 0.86934358,
        0.59294551],
       ...,
       [0.78529396, 0.82106605, 0.31580102, ..., 0.65562953, 0.52299584,
        0.18896786],
       [0.73688068, 0.50214931, 0.53107982, ..., 0.18891377, 0.72744301,
        0.46264225],
       [0.40904646, 0.43945995, 0.25989162, ..., 0.59846135, 0.31149513,
        0.36298992]])

In [ ]:
y_pred = model.predict(test_data) # zwraca prawdopodobienstwa dla danej klasy

1/1 [==============================] - 0s 23ms/step


In [ ]:
y_pred_class = np.argmax(y_pred, axis=1)
y_pred_class

array([6, 3, 2, 3, 3, 3, 3, 3, 2, 6])

# Regresja

In [ ]:
data = np.random.random((10000, 150))
labels = 50 * np.random.random(10000)

print(data.shape)
print(labels.shape)

(10000, 150)
(10000,)


In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1)) # przy prsewidywaniu ciaglych dajemy tu 1, aktywacja domyslnie liniowa

model.compile(optimizer='rmsprop', loss='mse') # metryka domyslnie taka sama mse

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
250/250 [==============================] - 1s 3ms/step - loss: 254.3883 - val_loss: 213.2599
Epoch 2/30
250/250 [==============================] - 0s 2ms/step - loss: 210.5870 - val_loss: 213.2969
Epoch 3/30
250/250 [==============================] - 1s 2ms/step - loss: 210.3518 - val_loss: 213.3860
Epoch 4/30
250/250 [==============================] - 1s 2ms/step - loss: 210.0237 - val_loss: 213.4350
Epoch 5/30
250/250 [==============================] - 1s 3ms/step - loss: 209.5908 - val_loss: 213.5068
Epoch 6/30
250/250 [==============================] - 1s 3ms/step - loss: 209.4245 - val_loss: 214.2759
Epoch 7/30
250/250 [==============================] - 1s 3ms/step - loss: 209.0368 - val_loss: 213.6963
Epoch 8/30
250/250 [==============================] - 1s 2ms/step - loss: 209.0015 - val_loss: 213.7534
Epoch 9/30
250/250 [==============================] - 1s 2ms/step - loss: 208.6120 - val_loss: 214.6656
Epoch 10/30
250/250 [==============================] - 0s 2ms/st

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1)) # przy prsewidywaniu ciaglych dajemy tu 1, aktywacja domyslnie liniowa

model.compile(optimizer='rmsprop', loss='mae', metrics=['mse'])

model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)
# tu widzimy i funkcje straty i metrics

Epoch 1/10
250/250 [==============================] - 1s 3ms/step - loss: 13.6413 - mse: 264.8015 - val_loss: 12.6440 - val_mse: 212.6848
Epoch 2/10
250/250 [==============================] - 1s 2ms/step - loss: 12.5446 - mse: 211.0229 - val_loss: 12.6759 - val_mse: 213.9387
Epoch 3/10
250/250 [==============================] - 1s 2ms/step - loss: 12.5381 - mse: 211.0556 - val_loss: 12.6469 - val_mse: 212.8841
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 12.5138 - mse: 210.5492 - val_loss: 12.6645 - val_mse: 213.9447
Epoch 5/10
250/250 [==============================] - 1s 2ms/step - loss: 12.5053 - mse: 210.0220 - val_loss: 12.6556 - val_mse: 213.2060
Epoch 6/10
250/250 [==============================] - 1s 2ms/step - loss: 12.5017 - mse: 210.0098 - val_loss: 12.6553 - val_mse: 213.2926
Epoch 7/10
250/250 [==============================] - 1s 2ms/step - loss: 12.4894 - mse: 209.7039 - val_loss: 12.6604 - val_mse: 213.5224
Epoch 8/10
250/250 [==============